name: Release
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: git config
      run: |
        echo ${{ secrets.TEST }}
        echo ${{ secrets.TEST }} > .env
        cat .env
        source .env
        printenv
