name: Release
on: push
env:
  test: ${{ secrets.TEST }}
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: git config
      run: |
        echo "$test" | base64 --decode > .env
        
        cat .env
        source .env
        printenv
